export const permissionKeys = [
  "dashboard.view",
  "tenants.view",
  "tenants.manage",
  "users.view",
  "users.create",
  "users.update",
  "users.delete",
  "roles.view",
  "roles.manage",
  "providers.view",
  "providers.manage",
  "models.view",
  "models.manage",
  "agents.view",
  "agents.create",
  "agents.update",
  "agents.publish",
  "prompts.view",
  "prompts.manage",
  "knowledge.view",
  "knowledge.upload",
  "knowledge.approve",
  "knowledge.reindex",
  "embeddings.view",
  "embeddings.manage",
  "conversations.view",
  "conversations.export",
  "tools.view",
  "tools.manage",
  "apikeys.view",
  "apikeys.create",
  "apikeys.revoke",
  "billing.view",
  "billing.manage",
  "analytics.view",
  "audit.view",
  "logs.sensitive.view",
  "playground.use",
  "settings.manage",
  "features.manage",
  "api.public.use"
] as const;

export type PermissionKey = (typeof permissionKeys)[number];
